# Generated by Django 2.2.28 on 2023-03-13 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('ingredients', models.CharField(max_length=4096)),
                ('instructions', models.CharField(max_length=4096)),
                ('category', models.CharField(choices=[('C', 'Cooking'), ('B', 'Baking')], max_length=128)),
                ('cuisine', models.CharField(choices=[('Cooking', (('CHINESE', 'Chinese'), ('INDIAN', 'Indian'), ('ITALIAN', 'Italian'), ('GREEK', 'Greek'), ('MEXICAN', 'Mexican'), ('THAI', 'Thai'))), ('Baking', (('BREAD', 'Bread'), ('BROWNIES', 'Brownies'), ('CAKE', 'Cake'), ('COOKIES', 'Cookies'), ('CUPCAKES', 'Cupcakes'), ('PASTRIES', 'Pastries')))], max_length=128)),
                ('author', models.CharField(default='', max_length=64)),
                ('image', models.ImageField(upload_to='')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('emailAddress', models.EmailField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLikesRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yumyay.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
